Add some alignments for seasonal subscriptions
Cleeng/mediastore-sdk pull request #219
Opened 2023-04-19 12:25 UTC by pawelacio

### Description 

Some modification in current plan and checkout to handle seasonal subscription type

### Screenshots 
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/19149811/233073003-4ca3c7cb-4b52-4e46-aed4-2d1df8b8041d.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/19149811/233073150-3c09a743-fef3-48f7-9848-8887f634f2ac.png">

2023-04-19 12:52 UTC, kjhank requested changes

2023-04-19 12:52 UTC, kjhank commented on src/components/Price/Price.js
> +  return (
Why the explicit return?

2023-04-25 10:13 UTC, pawelacio commented on src/components/Price/Price.js
> +  return (
I forgot abut that. Already changed it.

2023-04-25 10:18 UTC, kjhank submitted a review, later dismissed

2023-05-16 09:27 UTC, merged